<?php
/**
 * @file
 * Create and manage JBrowse instances.
 */

require_once 'includes/hardwoods_jbrowse.api.inc';
require_once 'includes/hardwoods_jbrowse.jobs.inc';
require_once 'includes/hardwoods_jbrowse_commands.inc';

/**
 * Implements hook_menu().
 */
function hardwoods_jbrowse_menu() {
  $items = [];

  // Admin forms
  $items['admin/hardwoods_jbrowse'] = [
    'title' => 'JBrowse',
    'description' => 'List JBrowse settings',
    'page callback' => 'hardwoods_jbrowse_instances_page',
    'page arguments' => ['hardwoods_jbrowse_configure_form'],
    'access arguments' => ['administer hardwoods jbrowse'],
    'file' => 'includes/hardwoods_jbrowse_list.page.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['admin/hardwoods_jbrowse/list'] = [
    'title' => 'List Instances',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  ];

  $items['admin/hardwoods_jbrowse/configure'] = [
    'title' => 'Settings',
    'description' => 'List and create JBrowse instances.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['hardwoods_jbrowse_configure_form'],
    'access arguments' => ['configure hardwoods jbrowse'],
    'file' => 'includes/hardwoods_jbrowse_configure.form.inc',
    'type' => MENU_LOCAL_TASK,
  ];

  $items['admin/hardwoods_jbrowse/instances/add'] = [
    'title' => 'Add New Instance',
    'description' => 'List and create JBrowse instances.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['hardwoods_jbrowse_add_form'],
    'access arguments' => ['administer hardwoods jbrowse'],
    'file' => 'includes/hardwoods_jbrowse_add.form.inc',
    'type' => MENU_LOCAL_ACTION,
  ];

  $items['admin/hardwoods_jbrowse/instances/%'] = [
    'title' => 'Manage Instance',
    'description' => 'View an instance and manage its tracks.',
    'page callback' => 'hardwoods_jbrowse_instance_page',
    'page arguments' => [3],
    'access arguments' => ['administer hardwoods jbrowse'],
    'file' => 'includes/hardwoods_jbrowse_instance.page.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['admin/hardwoods_jbrowse/instances/%/add_track'] = [
    'title' => 'Add New Track',
    'description' => 'Add new track to a jbrowse instance.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['hardwoods_jbrowse_add_track_form', 3],
    'access arguments' => ['administer hardwoods jbrowse'],
    'file' => 'includes/hardwoods_jbrowse_tracks.form.inc',
    'type' => MENU_LOCAL_ACTION,
  ];

  //  $items['admin/hardwoods_jbrowse/instances/%/edit_track/%'] = [
  //    'title' => 'Add New Instance',
  //    'description' => 'List and create JBrowse instances.',
  //    'page callback' => 'drupal_get_form',
  //    'page arguments' => ['hardwoods_jbrowse_add_form'],
  //    'access arguments' => ['administer hardwoods jbrowse'],
  //    'file' => 'includes/hardwoods_jbrowse_add.form.inc',
  //    'type' => MENU_LOCAL_ACTION,
  //  ];
  //
  //  $items['admin/hardwoods_jbrowse/instances/%/remove_track'] = [
  //    'title' => 'Add New Instance',
  //    'description' => 'List and create JBrowse instances.',
  //    'page callback' => 'drupal_get_form',
  //    'page arguments' => ['hardwoods_jbrowse_add_form'],
  //    'access arguments' => ['administer hardwoods jbrowse'],
  //    'file' => 'includes/hardwoods_jbrowse_add.form.inc',
  //    'type' => MENU_LOCAL_ACTION,
  //  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function hardwoods_jbrowse_permission() {
  $items = [];

  $items['configure hardwoods jbrowse'] = [
    'title' => t('Configure Hardwoods JBrowse'),
  ];

  $items['administer hardwoods jbrowse'] = [
    'title' => t('Create, edit and delete JBrowse instances'),
  ];

  return $items;
}
